[package]
name = "proyecto_empresa_b"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "2.6.2"
serde_json = "1.0.94"
serde = { version= "1.0.156", features= ["derive"] }
